# Generated by Django 4.2 on 2023-04-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_train_data', models.BooleanField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.market')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pair')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainedohlc',
            name='market',
        ),
        migrations.RemoveField(
            model_name='trainedohlc',
            name='pair',
        ),
        migrations.DeleteModel(
            name='CurrentOHLC',
        ),
        migrations.DeleteModel(
            name='TrainedOHLC',
        ),
    ]
