# Generated by Django 4.2 on 2023-04-14 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_ohlc_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohlc',
            name='datetime',
        ),
        migrations.AddField(
            model_name='ohlc',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
