# Generated by Django 4.2 on 2023-04-22 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_ohlc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserNetAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCurrnecy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_training.currency')),
                ('net_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_training.usernetasset')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.FloatField()),
                ('net_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_training.usernetasset')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pair')),
            ],
        ),
        migrations.CreateModel(
            name='BidAsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('asd', models.FloatField()),
                ('datetime', models.DateTimeField(null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pair')),
            ],
        ),
    ]
