# Generated by Django 4.2 on 2023-04-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_training', '0002_rename_bidasd_bidask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidask',
            old_name='asd',
            new_name='ask',
        ),
    ]
