# Generated by Django 4.2 on 2023-04-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_training', '0003_rename_asd_bidask_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
